project_name: sysgreet

before:
  hooks:
    - go mod tidy

builds:
  - id: sysgreet
    main: ./cmd/sysgreet
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: binary
    builds: [sysgreet]
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - configs/example.yaml
      - configs/example.toml

checksum:
  name_template: "checksums.txt"

dockers: []

dist: dist

release:
  github:
    owner: veteranbv
    name: sysgreet

changelog:
  use: git
