# Default Hostinfo configuration (YAML)
display:
  hostname: true
  os: true
  ip_addresses: true
  remote_ip: true
  uptime: true
  user: true
  memory: true
  disk: true
  load: true
  datetime: true
  last_login: true

ascii:
  font: "random"
  color: "random"
  monochrome: false

layout:
  compact: false
  sections:
    - header
    - system
    - network
    - resources

network:
  show_interface_names: true
  max_interfaces: 3
