# Sysgreet configuration reference (TOML)
[display]
hostname = true
os = true
ip_addresses = true
remote_ip = true
uptime = true
user = true
memory = true
disk = true
load = true
datetime = true
last_login = true

[ascii]
# Font options: "ANSI Regular", "ANSI Shadow", "Block", "DOS Rebel", "Basic", "standard", "slant"
font = "ANSI Regular"

# Gradient: cycle colors per line (overrides 'color' if set)
gradient = ["brightblue", "blue", "cyan", "brightcyan", "white"]

# Single color: use one color for entire banner (ignored if gradient is set)
# color = "cyan"

# Monochrome: disable all colors
monochrome = false

[layout]
compact = false
sections = ["header", "network", "system", "resources"]

[network]
show_interface_names = true
max_interfaces = 5
