name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run Tests
        env:
          CGO_ENABLED: 0
        run: |
          go test ./...
          go test -bench Startup ./test/benchmarks
      - name: Validate go install path
        run: |
          go install ./cmd/hostinfo
          hostinfo --disable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
